services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dowstats-web
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NUXT_DB_HOST: ${NUXT_DB_HOST}
      NUXT_DB_PORT: ${NUXT_DB_PORT:-3306}
      NUXT_DB_USER: ${NUXT_DB_USER}
      NUXT_DB_PASSWORD: ${NUXT_DB_PASSWORD}
      NUXT_DB_NAME: ${NUXT_DB_NAME}
    env_file:
      - .env
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
