openapi: 3.0.3
info:
  title: RelicLink API for Dawn of War
  version: 1.0.0
  description: |
    This is a partial documentation of the RelicLink public API used by games such as Dawn of War: Soulstorm (DoW1-DE).
    The API is mostly REST-like and returns JSON responses. This spec covers key endpoints based on reverse-engineered usage.

    **Note:** Expect CORS-errors with `https://dow-api.reliclink.com` in the browser.
    Use a server-side middleware to avoid this.
    ---
  license:
    name: Source (Steam Community post by "Reuben")
    url: https://steamcommunity.com/app/3556750/discussions/0/592906686979714916/

servers:
  - url: /api/proxy/relic
  - url: https://dow-api.reliclink.com

tags:
  - name: Community API
    description: Public API endpoints for community applications and websites
  - name: Game API - Leaderboard
    description: In-game API endpoints for leaderboard data

paths:
  /community/leaderboard/getrecentmatchhistory:
    get:
      tags:
        - Community API
        
      summary: Get Recent Match History
      description: Returns the recent match history for one or more players.
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            example: dow1-de
          description: Game identifier (e.g., "dow1-de" for Dawn of War)
        - name: aliases
          in: query
          required: true
          schema:
            type: string
            example: '["4str3"]'
          description: JSON array string containing player aliases (nicknames)
      responses:
        '200':
          description: Recent match history returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecentMatchHistoryResponse'
              example:
                result:
                  code: 0
                  message: OK
                matchHistoryStats:
                  - id: 800789
                    creator_profile_id: 10334711
                    mapname: 4P_DREAD_PEAK
                    matchtype_id: 2
                    startgametime: 1756418585
                    completiontime: 1756419020
                    matchhistorymember:
                      - profile_id: 10729783
                        race_id: 7
                        teamid: 1
                        wins: 3
                        losses: 5
                        outcome: 1
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /community/leaderboard/getrecentmatchhistorybyprofileid:
    get:
      tags:
        - Community API
        
      summary: Get Recent Match History By Profile ID
      description: Returns the recent match history for a specific player profile ID.
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            example: dow1-de
          description: Game identifier (e.g., "dow1-de" for Dawn of War)
        - name: profile_id
          in: query
          required: true
          schema:
            type: integer
            example: 10729783
          description: Relic profile ID of the player
      responses:
        '200':
          description: Recent match history returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecentMatchHistoryByProfileIdResponse'
              example:
                result:
                  code: 0
                  message: OK
                matchHistoryStats:
                  - id: 800789
                    creator_profile_id: 10334711
                    mapname: 4P_DREAD_PEAK
                    matchtype_id: 2
                    startgametime: 1756418585
                    completiontime: 1756419020
                    slotinfo:
                      team1: [10729783, 10334711]
                      team2: [11851962, 10445236]
                    matchhistorymember:
                      - profile_id: 10729783
                        race_id: 7
                        teamid: 1
                        wins: 3
                        losses: 5
                        outcome: 1
                      - profile_id: 10334711
                        race_id: 5
                        teamid: 1
                        wins: 10
                        losses: 2
                        outcome: 1
                profiles: []
        '400':
          description: Invalid request parameters
        '500':
          description: Server error

  /community/leaderboard/getavailableleaderboards:
    get:
      tags:
        - Community API
        
      summary: Get Available Leaderboards
      description: Returns available leaderboards for the specified game.
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            example: dow1-de
          description: Game identifier
      responses:
        '200':
          description: Leaderboard list returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AvailableLeaderboardsResponse'
              example:
                result:
                  code: 0
                  message: SUCCESS
                leaderboards:
                  - id: 1
                    name: 1v1
                    isranked: 1
                    leaderboardmap:
                      - matchtype_id: 1
                        statgroup_type: 1
                        race_id: 0
                matchTypes:
                  - id: 1
                    name: 1v1
                    locstringid: -1
                races:
                  - id: 0
                    name: chaos_marine_race
                    faction_id: 0
                    locstringid: -1
                factions: []
                leaderboardRegions: []
        '400':
          description: Missing or invalid game title
        '500':
          description: Internal server error

  /community/leaderboard/getpersonalstat:
    get:
      tags:
        - Community API
        
      summary: Get Personal Stats
      description: Returns stats for player profile IDs or profile names.
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            example: dow1-de
          description: Game identifier
        - name: profile_ids
          in: query
          required: false
          schema:
            type: string
            example: '[10729783]'
          description: JSON array string of player profile IDs
        - name: profile_names
          in: query
          required: false
          schema:
            type: string
            example: '["/steam/76561198029454731"]'
          description: JSON array string containing player profile names (e.g. Steam IDs)
      responses:
        '200':
          description: Player statistics returned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalStatsResponse'
              example:
                result:
                  code: 0
                  message: SUCCESS
                statGroups:
                  - id: 5151
                    name: 4str3
                    type: 1
                    members:
                      - profile_id: 10729783
                        name: 4str3
                leaderboardStats:
                  - statgroup_id: 5151
                    leaderboard_id: 1
                    wins: 10
                    losses: 5
                    streak: 2
                    disputes: 0
                    drops: 0
                    rank: 123
                    ranktotal: 349
                    ranklevel: 1
                    regionrank: 100
                    regionranktotal: 200
                    lastmatchdate: 1700000000
                    highestrank: 100
                    highestranklevel: 1
        '400':
          description: Invalid or missing profile IDs/names
        '500':
          description: API server error

  /community/leaderboard/getleaderboard2:
    get:
      tags:
        - Community API
        
      summary: Get Leaderboard Rankings
      description: Retrieves leaderboard data with pagination and sorting.
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            example: dow1-de
          description: Game identifier
        - name: leaderboard_id
          in: query
          required: true
          schema:
            type: integer
            example: 1
          description: ID of the leaderboard to retrieve
        - name: sortBy
          in: query
          required: false
          schema:
            type: integer
            example: 0
          description: Field to sort results by
        - name: start
          in: query
          required: false
          schema:
            type: integer
            example: 1
          description: Starting position for pagination
        - name: count
          in: query
          required: false
          schema:
            type: integer
            example: 50
          description: Number of results to return
      responses:
        '200':
          description: Leaderboard entries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Leaderboard2Response'
              example:
                result:
                  code: 0
                  message: SUCCESS
                statGroups:
                  - id: 5151
                    name: 4str3
                    type: 1
                    members:
                      - profile_id: 10729783
                        name: 4str3
                  - id: 5152
                    name: ally
                    type: 1
                    members:
                      - profile_id: 10334711
                        name: ally
                leaderboardStats:
                  - statgroup_id: 5151
                    leaderboard_id: 1
                    wins: 70
                    losses: 18
                    streak: 5
                    disputes: 0
                    drops: 1
                    rank: 1
                    ranktotal: 349
                    ranklevel: 1
                    regionrank: 1
                    regionranktotal: 100
                    lastmatchdate: 1700000000
                    highestrank: 1
                    highestranklevel: 1
                rankTotal: 349
        '400':
          description: Invalid leaderboard parameters
        '500':
          description: Internal API error

components:
  schemas:
    AvailableLeaderboardsResponse:
      type: object
      description: Response containing list of available leaderboards for the specified game.
      properties:
        result:
          type: object
          description: Result object returned by API (0 indicates success via code)
          properties:
            code:
              type: integer
              description: Result code (0 indicates success)
              example: 0
            message:
              type: string
              description: Result message
              example: SUCCESS
          required: [code, message]
        leaderboards:
          type: array
          items:
            $ref: '#/components/schemas/LeaderboardInfo'
        matchTypes:
          type: array
          items:
            $ref: '#/components/schemas/MatchType'
        races:
          type: array
          items:
            $ref: '#/components/schemas/Race'
        factions:
          type: array
          items:
            $ref: '#/components/schemas/Faction'
        leaderboardRegions:
          type: array
          items:
            $ref: '#/components/schemas/LeaderboardRegion'
      required: [result, leaderboards]

    LeaderboardInfo:
      type: object
      description: Leaderboard basic information.
      properties:
        id:
          type: integer
          description: Leaderboard identifier
        name:
          type: string
          description: Display name
        description:
          type: string
          description: Human readable description
        isranked:
          type: integer
          description: Ranked flag (1 ranked, 0 unranked)
        leaderboardmap:
          type: array
          description: Mapping to match type, statgroup type and race
          items:
            $ref: '#/components/schemas/LeaderboardMapEntry'
      required: [id, name]

    LeaderboardMapEntry:
      type: object
      description: Mapping entry for leaderboard to match type/stat group type/race.
      properties:
        matchtype_id:
          type: integer
        statgroup_type:
          type: integer
        race_id:
          type: integer
      required: [matchtype_id, statgroup_type, race_id]

    MatchType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        locstringid:
          type: integer
      required: [id, name]

    Race:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        faction_id:
          type: integer
        locstringid:
          type: integer
      required: [id, name]

    Faction:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        locstringid:
          type: integer
      required: [id, name]

    LeaderboardRegion:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required: [id, name]

    PersonalStatsResponse:
      type: object
      description: Response containing personal statistics for one or more profiles.
      properties:
        result:
          type: object
          description: Result object returned by API (0 indicates success via code)
          properties:
            code:
              type: integer
              description: Result code (0 indicates success)
              example: 0
            message:
              type: string
              description: Result message
              example: SUCCESS
          required: [code, message]
        statGroups:
          type: array
          description: Stat groups related to the requested profiles
          items:
            $ref: '#/components/schemas/StatGroup'
        leaderboardStats:
          type: array
          description: Statistics entries for the requested profiles on relevant leaderboards
          items:
            $ref: '#/components/schemas/LeaderboardStat'
      required: [result, statGroups, leaderboardStats]

    # PersonalStat schema removed as unused
    
    Leaderboard2Response:
      type: object
      description: Leaderboard data including entries and stat group details.
      properties:
        result:
          type: object
          description: Result object returned by API (0 indicates success via code)
          properties:
            code:
              type: integer
              description: Result code (0 indicates success)
              example: 0
            message:
              type: string
              description: Result message
              example: SUCCESS
          required: [code, message]
        leaderboardStats:
          type: array
          description: List of leaderboard entries
          items:
            $ref: '#/components/schemas/LeaderboardStat'
        statGroups:
          type: array
          description: List of stat groups
          items:
            $ref: '#/components/schemas/StatGroup'
        rankTotal:
          type: integer
          description: Total number of ranked entries in this leaderboard
      required: [result, leaderboardStats, statGroups]

    LeaderboardStat:
      type: object
      description: Leaderboard statistics entry for a stat group.
      properties:
        statgroup_id:
          type: integer
          description: Stat group identifier this entry belongs to
        leaderboard_id:
          type: integer
        wins:
          type: integer
        losses:
          type: integer
        streak:
          type: integer
        disputes:
          type: integer
        drops:
          type: integer
        rank:
          type: integer
        ranktotal:
          type: integer
        ranklevel:
          type: integer
        regionrank:
          type: integer
        regionranktotal:
          type: integer
        lastmatchdate:
          type: integer
          description: Unix timestamp of the last match
        highestrank:
          type: integer
        highestranklevel:
          type: integer
      required: [statgroup_id, leaderboard_id, rank]

    # LeaderboardEntry schema removed as unused

    StatGroup:
      type: object
      description: Stat group details describing arranged team or solo grouping.
      properties:
        id:
          type: integer
          description: Stat group identifier
        name:
          type: string
          description: Group name (if available)
        type:
          type: integer
          description: Group type code
        members:
          type: array
          description: Members of the group
          items:
            $ref: '#/components/schemas/StatGroupMember'
      required: [id, type, members]

    StatGroupMember:
      type: object
      description: Member entry inside a stat group.
      properties:
        profile_id:
          type: integer
          description: Member profile identifier
        name:
          type: string
          description: Member display name
        alias:
          type: string
          description: Member alias (nickname)
        personal_statgroup_id:
          type: integer
          description: Personal stat group id
        xp:
          type: integer
        level:
          type: integer
        leaderboardregion_id:
          type: integer
        country:
          type: string
      required: [profile_id, name]
