name: Build & Deploy Nuxt

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t dowstats:latest .

      - name: Push Docker image
        run: docker tag dowstats:latest ${{ secrets.DOCKER_USERNAME }}/dowstats:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/dowstats:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/dowstats:latest
            docker stop dowstats || true
            docker rm dowstats || true
            docker run -d \
              --name dowstats \
              -p 3000:3000 \
              -e NUXT_DB_HOST=${{ secrets.NUXT_DB_HOST }} \
              -e NUXT_DB_PORT=${{ secrets.NUXT_DB_PORT }} \
              -e NUXT_DB_USER=${{ secrets.NUXT_DB_USER }} \
              -e NUXT_DB_PASSWORD=${{ secrets.NUXT_DB_PASSWORD }} \
              -e NUXT_DB_NAME=${{ secrets.NUXT_DB_NAME }} \
              ${{ secrets.DOCKER_USERNAME }}/dowstats:latest
